// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module data_gen_continue_config_data_gen_continue_config_Pipeline_data_gen_label0 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        Output_2_V_TREADY,
        Output_2_V_TDATA,
        Output_2_V_TVALID
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   Output_2_V_TREADY;
output  [511:0] Output_2_V_TDATA;
output   Output_2_V_TVALID;

reg ap_idle;
reg Output_2_V_TVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln29_fu_530_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [11:0] triangle_3ds_x0_V_address0;
reg    triangle_3ds_x0_V_ce0;
wire   [7:0] triangle_3ds_x0_V_q0;
wire   [11:0] triangle_3ds_x0_V_address1;
reg    triangle_3ds_x0_V_ce1;
wire   [7:0] triangle_3ds_x0_V_q1;
wire   [11:0] triangle_3ds_x0_V_address2;
reg    triangle_3ds_x0_V_ce2;
wire   [7:0] triangle_3ds_x0_V_q2;
wire   [11:0] triangle_3ds_x0_V_address3;
reg    triangle_3ds_x0_V_ce3;
wire   [7:0] triangle_3ds_x0_V_q3;
wire   [11:0] triangle_3ds_y0_V_address0;
reg    triangle_3ds_y0_V_ce0;
wire   [7:0] triangle_3ds_y0_V_q0;
wire   [11:0] triangle_3ds_y0_V_address1;
reg    triangle_3ds_y0_V_ce1;
wire   [7:0] triangle_3ds_y0_V_q1;
wire   [11:0] triangle_3ds_y0_V_address2;
reg    triangle_3ds_y0_V_ce2;
wire   [7:0] triangle_3ds_y0_V_q2;
wire   [11:0] triangle_3ds_y0_V_address3;
reg    triangle_3ds_y0_V_ce3;
wire   [7:0] triangle_3ds_y0_V_q3;
wire   [11:0] triangle_3ds_z0_V_address0;
reg    triangle_3ds_z0_V_ce0;
wire   [7:0] triangle_3ds_z0_V_q0;
wire   [11:0] triangle_3ds_z0_V_address1;
reg    triangle_3ds_z0_V_ce1;
wire   [7:0] triangle_3ds_z0_V_q1;
wire   [11:0] triangle_3ds_z0_V_address2;
reg    triangle_3ds_z0_V_ce2;
wire   [7:0] triangle_3ds_z0_V_q2;
wire   [11:0] triangle_3ds_z0_V_address3;
reg    triangle_3ds_z0_V_ce3;
wire   [7:0] triangle_3ds_z0_V_q3;
wire   [11:0] triangle_3ds_x1_V_address0;
reg    triangle_3ds_x1_V_ce0;
wire   [7:0] triangle_3ds_x1_V_q0;
wire   [11:0] triangle_3ds_x1_V_address1;
reg    triangle_3ds_x1_V_ce1;
wire   [7:0] triangle_3ds_x1_V_q1;
wire   [11:0] triangle_3ds_x1_V_address2;
reg    triangle_3ds_x1_V_ce2;
wire   [7:0] triangle_3ds_x1_V_q2;
wire   [11:0] triangle_3ds_x1_V_address3;
reg    triangle_3ds_x1_V_ce3;
wire   [7:0] triangle_3ds_x1_V_q3;
wire   [11:0] triangle_3ds_y1_V_address0;
reg    triangle_3ds_y1_V_ce0;
wire   [7:0] triangle_3ds_y1_V_q0;
wire   [11:0] triangle_3ds_y1_V_address1;
reg    triangle_3ds_y1_V_ce1;
wire   [7:0] triangle_3ds_y1_V_q1;
wire   [11:0] triangle_3ds_y1_V_address2;
reg    triangle_3ds_y1_V_ce2;
wire   [7:0] triangle_3ds_y1_V_q2;
wire   [11:0] triangle_3ds_y1_V_address3;
reg    triangle_3ds_y1_V_ce3;
wire   [7:0] triangle_3ds_y1_V_q3;
wire   [11:0] triangle_3ds_z1_V_address0;
reg    triangle_3ds_z1_V_ce0;
wire   [7:0] triangle_3ds_z1_V_q0;
wire   [11:0] triangle_3ds_z1_V_address1;
reg    triangle_3ds_z1_V_ce1;
wire   [7:0] triangle_3ds_z1_V_q1;
wire   [11:0] triangle_3ds_z1_V_address2;
reg    triangle_3ds_z1_V_ce2;
wire   [7:0] triangle_3ds_z1_V_q2;
wire   [11:0] triangle_3ds_z1_V_address3;
reg    triangle_3ds_z1_V_ce3;
wire   [7:0] triangle_3ds_z1_V_q3;
wire   [11:0] triangle_3ds_x2_V_address0;
reg    triangle_3ds_x2_V_ce0;
wire   [7:0] triangle_3ds_x2_V_q0;
wire   [11:0] triangle_3ds_x2_V_address1;
reg    triangle_3ds_x2_V_ce1;
wire   [7:0] triangle_3ds_x2_V_q1;
wire   [11:0] triangle_3ds_x2_V_address2;
reg    triangle_3ds_x2_V_ce2;
wire   [7:0] triangle_3ds_x2_V_q2;
wire   [11:0] triangle_3ds_x2_V_address3;
reg    triangle_3ds_x2_V_ce3;
wire   [7:0] triangle_3ds_x2_V_q3;
wire   [11:0] triangle_3ds_y2_V_address0;
reg    triangle_3ds_y2_V_ce0;
wire   [7:0] triangle_3ds_y2_V_q0;
wire   [11:0] triangle_3ds_y2_V_address1;
reg    triangle_3ds_y2_V_ce1;
wire   [7:0] triangle_3ds_y2_V_q1;
wire   [11:0] triangle_3ds_y2_V_address2;
reg    triangle_3ds_y2_V_ce2;
wire   [7:0] triangle_3ds_y2_V_q2;
wire   [11:0] triangle_3ds_y2_V_address3;
reg    triangle_3ds_y2_V_ce3;
wire   [7:0] triangle_3ds_y2_V_q3;
wire   [11:0] triangle_3ds_z2_V_address0;
reg    triangle_3ds_z2_V_ce0;
wire   [7:0] triangle_3ds_z2_V_q0;
wire   [11:0] triangle_3ds_z2_V_address1;
reg    triangle_3ds_z2_V_ce1;
wire   [7:0] triangle_3ds_z2_V_q1;
wire   [11:0] triangle_3ds_z2_V_address2;
reg    triangle_3ds_z2_V_ce2;
wire   [7:0] triangle_3ds_z2_V_q2;
wire   [11:0] triangle_3ds_z2_V_address3;
reg    triangle_3ds_z2_V_ce3;
wire   [7:0] triangle_3ds_z2_V_q3;
reg    Output_2_V_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln225_fu_550_p1;
wire   [63:0] zext_ln225_1_fu_569_p1;
wire   [63:0] zext_ln225_2_fu_588_p1;
wire   [63:0] zext_ln225_3_fu_607_p1;
reg   [9:0] i_fu_70;
wire    ap_loop_init;
reg   [9:0] ap_sig_allocacmp_i_1;
wire   [9:0] add_ln29_fu_536_p2;
reg    ap_block_pp0_stage0_01001;
wire   [11:0] shl_ln_fu_542_p3;
wire   [11:0] or_ln41_fu_563_p2;
wire   [11:0] or_ln52_fu_582_p2;
wire   [11:0] or_ln63_fu_601_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

data_gen_continue_config_data_gen_continue_config_Pipeline_data_gen_label0_triangle_3ds_x0_V #(
    .DataWidth( 8 ),
    .AddressRange( 3192 ),
    .AddressWidth( 12 ))
triangle_3ds_x0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(triangle_3ds_x0_V_address0),
    .ce0(triangle_3ds_x0_V_ce0),
    .q0(triangle_3ds_x0_V_q0),
    .address1(triangle_3ds_x0_V_address1),
    .ce1(triangle_3ds_x0_V_ce1),
    .q1(triangle_3ds_x0_V_q1),
    .address2(triangle_3ds_x0_V_address2),
    .ce2(triangle_3ds_x0_V_ce2),
    .q2(triangle_3ds_x0_V_q2),
    .address3(triangle_3ds_x0_V_address3),
    .ce3(triangle_3ds_x0_V_ce3),
    .q3(triangle_3ds_x0_V_q3)
);

data_gen_continue_config_data_gen_continue_config_Pipeline_data_gen_label0_triangle_3ds_y0_V #(
    .DataWidth( 8 ),
    .AddressRange( 3192 ),
    .AddressWidth( 12 ))
triangle_3ds_y0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(triangle_3ds_y0_V_address0),
    .ce0(triangle_3ds_y0_V_ce0),
    .q0(triangle_3ds_y0_V_q0),
    .address1(triangle_3ds_y0_V_address1),
    .ce1(triangle_3ds_y0_V_ce1),
    .q1(triangle_3ds_y0_V_q1),
    .address2(triangle_3ds_y0_V_address2),
    .ce2(triangle_3ds_y0_V_ce2),
    .q2(triangle_3ds_y0_V_q2),
    .address3(triangle_3ds_y0_V_address3),
    .ce3(triangle_3ds_y0_V_ce3),
    .q3(triangle_3ds_y0_V_q3)
);

data_gen_continue_config_data_gen_continue_config_Pipeline_data_gen_label0_triangle_3ds_z0_V #(
    .DataWidth( 8 ),
    .AddressRange( 3192 ),
    .AddressWidth( 12 ))
triangle_3ds_z0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(triangle_3ds_z0_V_address0),
    .ce0(triangle_3ds_z0_V_ce0),
    .q0(triangle_3ds_z0_V_q0),
    .address1(triangle_3ds_z0_V_address1),
    .ce1(triangle_3ds_z0_V_ce1),
    .q1(triangle_3ds_z0_V_q1),
    .address2(triangle_3ds_z0_V_address2),
    .ce2(triangle_3ds_z0_V_ce2),
    .q2(triangle_3ds_z0_V_q2),
    .address3(triangle_3ds_z0_V_address3),
    .ce3(triangle_3ds_z0_V_ce3),
    .q3(triangle_3ds_z0_V_q3)
);

data_gen_continue_config_data_gen_continue_config_Pipeline_data_gen_label0_triangle_3ds_x1_V #(
    .DataWidth( 8 ),
    .AddressRange( 3192 ),
    .AddressWidth( 12 ))
triangle_3ds_x1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(triangle_3ds_x1_V_address0),
    .ce0(triangle_3ds_x1_V_ce0),
    .q0(triangle_3ds_x1_V_q0),
    .address1(triangle_3ds_x1_V_address1),
    .ce1(triangle_3ds_x1_V_ce1),
    .q1(triangle_3ds_x1_V_q1),
    .address2(triangle_3ds_x1_V_address2),
    .ce2(triangle_3ds_x1_V_ce2),
    .q2(triangle_3ds_x1_V_q2),
    .address3(triangle_3ds_x1_V_address3),
    .ce3(triangle_3ds_x1_V_ce3),
    .q3(triangle_3ds_x1_V_q3)
);

data_gen_continue_config_data_gen_continue_config_Pipeline_data_gen_label0_triangle_3ds_y1_V #(
    .DataWidth( 8 ),
    .AddressRange( 3192 ),
    .AddressWidth( 12 ))
triangle_3ds_y1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(triangle_3ds_y1_V_address0),
    .ce0(triangle_3ds_y1_V_ce0),
    .q0(triangle_3ds_y1_V_q0),
    .address1(triangle_3ds_y1_V_address1),
    .ce1(triangle_3ds_y1_V_ce1),
    .q1(triangle_3ds_y1_V_q1),
    .address2(triangle_3ds_y1_V_address2),
    .ce2(triangle_3ds_y1_V_ce2),
    .q2(triangle_3ds_y1_V_q2),
    .address3(triangle_3ds_y1_V_address3),
    .ce3(triangle_3ds_y1_V_ce3),
    .q3(triangle_3ds_y1_V_q3)
);

data_gen_continue_config_data_gen_continue_config_Pipeline_data_gen_label0_triangle_3ds_z1_V #(
    .DataWidth( 8 ),
    .AddressRange( 3192 ),
    .AddressWidth( 12 ))
triangle_3ds_z1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(triangle_3ds_z1_V_address0),
    .ce0(triangle_3ds_z1_V_ce0),
    .q0(triangle_3ds_z1_V_q0),
    .address1(triangle_3ds_z1_V_address1),
    .ce1(triangle_3ds_z1_V_ce1),
    .q1(triangle_3ds_z1_V_q1),
    .address2(triangle_3ds_z1_V_address2),
    .ce2(triangle_3ds_z1_V_ce2),
    .q2(triangle_3ds_z1_V_q2),
    .address3(triangle_3ds_z1_V_address3),
    .ce3(triangle_3ds_z1_V_ce3),
    .q3(triangle_3ds_z1_V_q3)
);

data_gen_continue_config_data_gen_continue_config_Pipeline_data_gen_label0_triangle_3ds_x2_V #(
    .DataWidth( 8 ),
    .AddressRange( 3192 ),
    .AddressWidth( 12 ))
triangle_3ds_x2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(triangle_3ds_x2_V_address0),
    .ce0(triangle_3ds_x2_V_ce0),
    .q0(triangle_3ds_x2_V_q0),
    .address1(triangle_3ds_x2_V_address1),
    .ce1(triangle_3ds_x2_V_ce1),
    .q1(triangle_3ds_x2_V_q1),
    .address2(triangle_3ds_x2_V_address2),
    .ce2(triangle_3ds_x2_V_ce2),
    .q2(triangle_3ds_x2_V_q2),
    .address3(triangle_3ds_x2_V_address3),
    .ce3(triangle_3ds_x2_V_ce3),
    .q3(triangle_3ds_x2_V_q3)
);

data_gen_continue_config_data_gen_continue_config_Pipeline_data_gen_label0_triangle_3ds_y2_V #(
    .DataWidth( 8 ),
    .AddressRange( 3192 ),
    .AddressWidth( 12 ))
triangle_3ds_y2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(triangle_3ds_y2_V_address0),
    .ce0(triangle_3ds_y2_V_ce0),
    .q0(triangle_3ds_y2_V_q0),
    .address1(triangle_3ds_y2_V_address1),
    .ce1(triangle_3ds_y2_V_ce1),
    .q1(triangle_3ds_y2_V_q1),
    .address2(triangle_3ds_y2_V_address2),
    .ce2(triangle_3ds_y2_V_ce2),
    .q2(triangle_3ds_y2_V_q2),
    .address3(triangle_3ds_y2_V_address3),
    .ce3(triangle_3ds_y2_V_ce3),
    .q3(triangle_3ds_y2_V_q3)
);

data_gen_continue_config_data_gen_continue_config_Pipeline_data_gen_label0_triangle_3ds_z2_V #(
    .DataWidth( 8 ),
    .AddressRange( 3192 ),
    .AddressWidth( 12 ))
triangle_3ds_z2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(triangle_3ds_z2_V_address0),
    .ce0(triangle_3ds_z2_V_ce0),
    .q0(triangle_3ds_z2_V_q0),
    .address1(triangle_3ds_z2_V_address1),
    .ce1(triangle_3ds_z2_V_ce1),
    .q1(triangle_3ds_z2_V_q1),
    .address2(triangle_3ds_z2_V_address2),
    .ce2(triangle_3ds_z2_V_ce2),
    .q2(triangle_3ds_z2_V_q2),
    .address3(triangle_3ds_z2_V_address3),
    .ce3(triangle_3ds_z2_V_ce3),
    .q3(triangle_3ds_z2_V_q3)
);

data_gen_continue_config_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln29_fu_530_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_70 <= add_ln29_fu_536_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_70 <= 10'd0;
        end
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Output_2_V_TDATA_blk_n = Output_2_V_TREADY;
    end else begin
        Output_2_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Output_2_V_TVALID = 1'b1;
    end else begin
        Output_2_V_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln29_fu_530_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_1 = 10'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_70;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        triangle_3ds_x0_V_ce0 = 1'b1;
    end else begin
        triangle_3ds_x0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        triangle_3ds_x0_V_ce1 = 1'b1;
    end else begin
        triangle_3ds_x0_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        triangle_3ds_x0_V_ce2 = 1'b1;
    end else begin
        triangle_3ds_x0_V_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        triangle_3ds_x0_V_ce3 = 1'b1;
    end else begin
        triangle_3ds_x0_V_ce3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        triangle_3ds_x1_V_ce0 = 1'b1;
    end else begin
        triangle_3ds_x1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        triangle_3ds_x1_V_ce1 = 1'b1;
    end else begin
        triangle_3ds_x1_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        triangle_3ds_x1_V_ce2 = 1'b1;
    end else begin
        triangle_3ds_x1_V_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        triangle_3ds_x1_V_ce3 = 1'b1;
    end else begin
        triangle_3ds_x1_V_ce3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        triangle_3ds_x2_V_ce0 = 1'b1;
    end else begin
        triangle_3ds_x2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        triangle_3ds_x2_V_ce1 = 1'b1;
    end else begin
        triangle_3ds_x2_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        triangle_3ds_x2_V_ce2 = 1'b1;
    end else begin
        triangle_3ds_x2_V_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        triangle_3ds_x2_V_ce3 = 1'b1;
    end else begin
        triangle_3ds_x2_V_ce3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        triangle_3ds_y0_V_ce0 = 1'b1;
    end else begin
        triangle_3ds_y0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        triangle_3ds_y0_V_ce1 = 1'b1;
    end else begin
        triangle_3ds_y0_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        triangle_3ds_y0_V_ce2 = 1'b1;
    end else begin
        triangle_3ds_y0_V_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        triangle_3ds_y0_V_ce3 = 1'b1;
    end else begin
        triangle_3ds_y0_V_ce3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        triangle_3ds_y1_V_ce0 = 1'b1;
    end else begin
        triangle_3ds_y1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        triangle_3ds_y1_V_ce1 = 1'b1;
    end else begin
        triangle_3ds_y1_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        triangle_3ds_y1_V_ce2 = 1'b1;
    end else begin
        triangle_3ds_y1_V_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        triangle_3ds_y1_V_ce3 = 1'b1;
    end else begin
        triangle_3ds_y1_V_ce3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        triangle_3ds_y2_V_ce0 = 1'b1;
    end else begin
        triangle_3ds_y2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        triangle_3ds_y2_V_ce1 = 1'b1;
    end else begin
        triangle_3ds_y2_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        triangle_3ds_y2_V_ce2 = 1'b1;
    end else begin
        triangle_3ds_y2_V_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        triangle_3ds_y2_V_ce3 = 1'b1;
    end else begin
        triangle_3ds_y2_V_ce3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        triangle_3ds_z0_V_ce0 = 1'b1;
    end else begin
        triangle_3ds_z0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        triangle_3ds_z0_V_ce1 = 1'b1;
    end else begin
        triangle_3ds_z0_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        triangle_3ds_z0_V_ce2 = 1'b1;
    end else begin
        triangle_3ds_z0_V_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        triangle_3ds_z0_V_ce3 = 1'b1;
    end else begin
        triangle_3ds_z0_V_ce3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        triangle_3ds_z1_V_ce0 = 1'b1;
    end else begin
        triangle_3ds_z1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        triangle_3ds_z1_V_ce1 = 1'b1;
    end else begin
        triangle_3ds_z1_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        triangle_3ds_z1_V_ce2 = 1'b1;
    end else begin
        triangle_3ds_z1_V_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        triangle_3ds_z1_V_ce3 = 1'b1;
    end else begin
        triangle_3ds_z1_V_ce3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        triangle_3ds_z2_V_ce0 = 1'b1;
    end else begin
        triangle_3ds_z2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        triangle_3ds_z2_V_ce1 = 1'b1;
    end else begin
        triangle_3ds_z2_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        triangle_3ds_z2_V_ce2 = 1'b1;
    end else begin
        triangle_3ds_z2_V_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        triangle_3ds_z2_V_ce3 = 1'b1;
    end else begin
        triangle_3ds_z2_V_ce3 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Output_2_V_TDATA = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{56'd0}, {triangle_3ds_z2_V_q0}}}, {triangle_3ds_y2_V_q0}}}, {triangle_3ds_x2_V_q0}}}, {triangle_3ds_z1_V_q0}}}, {triangle_3ds_y1_V_q0}}}, {triangle_3ds_x1_V_q0}}}, {triangle_3ds_z0_V_q0}}}, {triangle_3ds_y0_V_q0}}}, {triangle_3ds_x0_V_q0}}}, {56'd0}}}, {triangle_3ds_z2_V_q1}}}, {triangle_3ds_y2_V_q1}}}, {triangle_3ds_x2_V_q1}}}, {triangle_3ds_z1_V_q1}}}, {triangle_3ds_y1_V_q1}}}, {triangle_3ds_x1_V_q1}}}, {triangle_3ds_z0_V_q1}}}, {triangle_3ds_y0_V_q1}}}, {triangle_3ds_x0_V_q1}}}, {56'd0}}}, {triangle_3ds_z2_V_q2}}}, {triangle_3ds_y2_V_q2}}}, {triangle_3ds_x2_V_q2}}}, {triangle_3ds_z1_V_q2}}}, {triangle_3ds_y1_V_q2}}}, {triangle_3ds_x1_V_q2}}}, {triangle_3ds_z0_V_q2}}}, {triangle_3ds_y0_V_q2}}}, {triangle_3ds_x0_V_q2}}}, {56'd0}}}, {triangle_3ds_z2_V_q3}}}, {triangle_3ds_y2_V_q3}}}, {triangle_3ds_x2_V_q3}}}, {triangle_3ds_z1_V_q3}}}, {triangle_3ds_y1_V_q3}}}, {triangle_3ds_x1_V_q3}}}, {triangle_3ds_z0_V_q3}}}, {triangle_3ds_y0_V_q3}}}, {triangle_3ds_x0_V_q3}};

assign add_ln29_fu_536_p2 = (ap_sig_allocacmp_i_1 + 10'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((1'b0 == Output_2_V_TREADY) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((1'b0 == Output_2_V_TREADY) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((1'b0 == Output_2_V_TREADY) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (1'b0 == Output_2_V_TREADY);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln29_fu_530_p2 = ((ap_sig_allocacmp_i_1 == 10'd798) ? 1'b1 : 1'b0);

assign or_ln41_fu_563_p2 = (shl_ln_fu_542_p3 | 12'd1);

assign or_ln52_fu_582_p2 = (shl_ln_fu_542_p3 | 12'd2);

assign or_ln63_fu_601_p2 = (shl_ln_fu_542_p3 | 12'd3);

assign shl_ln_fu_542_p3 = {{ap_sig_allocacmp_i_1}, {2'd0}};

assign triangle_3ds_x0_V_address0 = zext_ln225_3_fu_607_p1;

assign triangle_3ds_x0_V_address1 = zext_ln225_2_fu_588_p1;

assign triangle_3ds_x0_V_address2 = zext_ln225_1_fu_569_p1;

assign triangle_3ds_x0_V_address3 = zext_ln225_fu_550_p1;

assign triangle_3ds_x1_V_address0 = zext_ln225_3_fu_607_p1;

assign triangle_3ds_x1_V_address1 = zext_ln225_2_fu_588_p1;

assign triangle_3ds_x1_V_address2 = zext_ln225_1_fu_569_p1;

assign triangle_3ds_x1_V_address3 = zext_ln225_fu_550_p1;

assign triangle_3ds_x2_V_address0 = zext_ln225_3_fu_607_p1;

assign triangle_3ds_x2_V_address1 = zext_ln225_2_fu_588_p1;

assign triangle_3ds_x2_V_address2 = zext_ln225_1_fu_569_p1;

assign triangle_3ds_x2_V_address3 = zext_ln225_fu_550_p1;

assign triangle_3ds_y0_V_address0 = zext_ln225_3_fu_607_p1;

assign triangle_3ds_y0_V_address1 = zext_ln225_2_fu_588_p1;

assign triangle_3ds_y0_V_address2 = zext_ln225_1_fu_569_p1;

assign triangle_3ds_y0_V_address3 = zext_ln225_fu_550_p1;

assign triangle_3ds_y1_V_address0 = zext_ln225_3_fu_607_p1;

assign triangle_3ds_y1_V_address1 = zext_ln225_2_fu_588_p1;

assign triangle_3ds_y1_V_address2 = zext_ln225_1_fu_569_p1;

assign triangle_3ds_y1_V_address3 = zext_ln225_fu_550_p1;

assign triangle_3ds_y2_V_address0 = zext_ln225_3_fu_607_p1;

assign triangle_3ds_y2_V_address1 = zext_ln225_2_fu_588_p1;

assign triangle_3ds_y2_V_address2 = zext_ln225_1_fu_569_p1;

assign triangle_3ds_y2_V_address3 = zext_ln225_fu_550_p1;

assign triangle_3ds_z0_V_address0 = zext_ln225_3_fu_607_p1;

assign triangle_3ds_z0_V_address1 = zext_ln225_2_fu_588_p1;

assign triangle_3ds_z0_V_address2 = zext_ln225_1_fu_569_p1;

assign triangle_3ds_z0_V_address3 = zext_ln225_fu_550_p1;

assign triangle_3ds_z1_V_address0 = zext_ln225_3_fu_607_p1;

assign triangle_3ds_z1_V_address1 = zext_ln225_2_fu_588_p1;

assign triangle_3ds_z1_V_address2 = zext_ln225_1_fu_569_p1;

assign triangle_3ds_z1_V_address3 = zext_ln225_fu_550_p1;

assign triangle_3ds_z2_V_address0 = zext_ln225_3_fu_607_p1;

assign triangle_3ds_z2_V_address1 = zext_ln225_2_fu_588_p1;

assign triangle_3ds_z2_V_address2 = zext_ln225_1_fu_569_p1;

assign triangle_3ds_z2_V_address3 = zext_ln225_fu_550_p1;

assign zext_ln225_1_fu_569_p1 = or_ln41_fu_563_p2;

assign zext_ln225_2_fu_588_p1 = or_ln52_fu_582_p2;

assign zext_ln225_3_fu_607_p1 = or_ln63_fu_601_p2;

assign zext_ln225_fu_550_p1 = shl_ln_fu_542_p3;

endmodule //data_gen_continue_config_data_gen_continue_config_Pipeline_data_gen_label0
