// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module output_collect_output_collect_Pipeline_STREAM_IN_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        Input_3_TVALID,
        Input_3_TDATA,
        Input_3_TREADY,
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_address0,
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_ce0,
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_we0,
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_d0,
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_address0,
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_ce0,
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_we0,
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_d0
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   Input_3_TVALID;
input  [63:0] Input_3_TDATA;
output   Input_3_TREADY;
output  [7:0] output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_address0;
output   output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_ce0;
output   output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_we0;
output  [63:0] output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_d0;
output  [7:0] output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_address0;
output   output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_ce0;
output   output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_we0;
output  [63:0] output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_d0;

reg ap_idle;
reg Input_3_TREADY;
reg output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_ce0;
reg output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_we0;
reg output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_ce0;
reg output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln31_fu_94_p2;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    Input_3_TDATA_blk_n;
wire   [63:0] zext_ln33_fu_124_p1;
reg   [7:0] i_2_fu_48;
wire   [7:0] add_ln31_fu_100_p2;
wire    ap_loop_init;
reg   [7:0] ap_sig_allocacmp_i;
wire   [0:0] trunc_ln33_fu_130_p1;
wire   [6:0] lshr_ln1_fu_106_p4;
wire   [7:0] zext_ln33_cast_fu_116_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
reg    ap_condition_126;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

output_collect_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_start_int == 1'b0) | ((1'b0 == Input_3_TVALID) & (icmp_ln31_fu_94_p2 == 1'd0))) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_126)) begin
        if ((icmp_ln31_fu_94_p2 == 1'd0)) begin
            i_2_fu_48 <= add_ln31_fu_100_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_2_fu_48 <= 8'd0;
        end
    end
end

always @ (*) begin
    if (((icmp_ln31_fu_94_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        Input_3_TDATA_blk_n = Input_3_TVALID;
    end else begin
        Input_3_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == Input_3_TVALID) & (icmp_ln31_fu_94_p2 == 1'd0))) & (icmp_ln31_fu_94_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        Input_3_TREADY = 1'b1;
    end else begin
        Input_3_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) | ((1'b0 == Input_3_TVALID) & (icmp_ln31_fu_94_p2 == 1'd0)))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == Input_3_TVALID) & (icmp_ln31_fu_94_p2 == 1'd0))) & (icmp_ln31_fu_94_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == Input_3_TVALID) & (icmp_ln31_fu_94_p2 == 1'd0))) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == Input_3_TVALID) & (icmp_ln31_fu_94_p2 == 1'd0))) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_i = 8'd0;
    end else begin
        ap_sig_allocacmp_i = i_2_fu_48;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == Input_3_TVALID) & (icmp_ln31_fu_94_p2 == 1'd0))) & (1'b1 == ap_CS_fsm_state1))) begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_ce0 = 1'b1;
    end else begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == Input_3_TVALID) & (icmp_ln31_fu_94_p2 == 1'd0))) & (trunc_ln33_fu_130_p1 == 1'd0) & (icmp_ln31_fu_94_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_we0 = 1'b1;
    end else begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == Input_3_TVALID) & (icmp_ln31_fu_94_p2 == 1'd0))) & (1'b1 == ap_CS_fsm_state1))) begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_ce0 = 1'b1;
    end else begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == Input_3_TVALID) & (icmp_ln31_fu_94_p2 == 1'd0))) & (trunc_ln33_fu_130_p1 == 1'd1) & (icmp_ln31_fu_94_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_we0 = 1'b1;
    end else begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln31_fu_100_p2 = (ap_sig_allocacmp_i + 8'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((1'b0 == Input_3_TVALID) & (icmp_ln31_fu_94_p2 == 1'd0)));
end

always @ (*) begin
    ap_condition_126 = (~((ap_start_int == 1'b0) | ((1'b0 == Input_3_TVALID) & (icmp_ln31_fu_94_p2 == 1'd0))) & (1'b1 == ap_CS_fsm_state1));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln31_fu_94_p2 = ((ap_sig_allocacmp_i == 8'd128) ? 1'b1 : 1'b0);

assign lshr_ln1_fu_106_p4 = {{ap_sig_allocacmp_i[7:1]}};

assign output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_address0 = zext_ln33_fu_124_p1;

assign output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_d0 = Input_3_TDATA;

assign output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_address0 = zext_ln33_fu_124_p1;

assign output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_d0 = Input_3_TDATA;

assign trunc_ln33_fu_130_p1 = ap_sig_allocacmp_i[0:0];

assign zext_ln33_cast_fu_116_p3 = {{1'd1}, {lshr_ln1_fu_106_p4}};

assign zext_ln33_fu_124_p1 = zext_ln33_cast_fu_116_p3;

endmodule //output_collect_output_collect_Pipeline_STREAM_IN_3
