// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="output_collect_output_collect,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu9eg-ffvb1156-2-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.086000,HLS_SYN_LAT=665,HLS_SYN_TPT=none,HLS_SYN_MEM=8,HLS_SYN_DSP=0,HLS_SYN_FF=81,HLS_SYN_LUT=739,HLS_VERSION=2022_1}" *)

module output_collect (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        Input_1_TDATA,
        Input_1_TVALID,
        Input_1_TREADY,
        Input_2_TDATA,
        Input_2_TVALID,
        Input_2_TREADY,
        Input_3_TDATA,
        Input_3_TVALID,
        Input_3_TREADY,
        Input_4_TDATA,
        Input_4_TVALID,
        Input_4_TREADY,
        Output_1_TDATA,
        Output_1_TVALID,
        Output_1_TREADY
);

parameter    ap_ST_fsm_state1 = 16'd1;
parameter    ap_ST_fsm_state2 = 16'd2;
parameter    ap_ST_fsm_state3 = 16'd4;
parameter    ap_ST_fsm_state4 = 16'd8;
parameter    ap_ST_fsm_state5 = 16'd16;
parameter    ap_ST_fsm_state6 = 16'd32;
parameter    ap_ST_fsm_state7 = 16'd64;
parameter    ap_ST_fsm_state8 = 16'd128;
parameter    ap_ST_fsm_state9 = 16'd256;
parameter    ap_ST_fsm_state10 = 16'd512;
parameter    ap_ST_fsm_state11 = 16'd1024;
parameter    ap_ST_fsm_state12 = 16'd2048;
parameter    ap_ST_fsm_state13 = 16'd4096;
parameter    ap_ST_fsm_state14 = 16'd8192;
parameter    ap_ST_fsm_state15 = 16'd16384;
parameter    ap_ST_fsm_state16 = 16'd32768;

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] Input_1_TDATA;
input   Input_1_TVALID;
output   Input_1_TREADY;
input  [63:0] Input_2_TDATA;
input   Input_2_TVALID;
output   Input_2_TREADY;
input  [63:0] Input_3_TDATA;
input   Input_3_TVALID;
output   Input_3_TREADY;
input  [63:0] Input_4_TDATA;
input   Input_4_TVALID;
output   Input_4_TREADY;
output  [255:0] Output_1_TDATA;
output   Output_1_TVALID;
input   Output_1_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [15:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [7:0] output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_address0;
reg    output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_ce0;
reg    output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_we0;
reg   [63:0] output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_d0;
wire   [63:0] output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_q0;
reg    output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_ce1;
wire   [63:0] output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_q1;
reg   [7:0] output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_address0;
reg    output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_ce0;
reg    output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_we0;
reg   [63:0] output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_d0;
wire   [63:0] output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_q0;
reg    output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_ce1;
wire   [63:0] output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_q1;
wire    grp_output_collect_Pipeline_STREAM_IN_1_fu_48_ap_start;
wire    grp_output_collect_Pipeline_STREAM_IN_1_fu_48_ap_done;
wire    grp_output_collect_Pipeline_STREAM_IN_1_fu_48_ap_idle;
wire    grp_output_collect_Pipeline_STREAM_IN_1_fu_48_ap_ready;
wire    grp_output_collect_Pipeline_STREAM_IN_1_fu_48_Input_1_TREADY;
wire   [7:0] grp_output_collect_Pipeline_STREAM_IN_1_fu_48_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_address0;
wire    grp_output_collect_Pipeline_STREAM_IN_1_fu_48_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_ce0;
wire    grp_output_collect_Pipeline_STREAM_IN_1_fu_48_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_we0;
wire   [63:0] grp_output_collect_Pipeline_STREAM_IN_1_fu_48_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_d0;
wire   [7:0] grp_output_collect_Pipeline_STREAM_IN_1_fu_48_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_address0;
wire    grp_output_collect_Pipeline_STREAM_IN_1_fu_48_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_ce0;
wire    grp_output_collect_Pipeline_STREAM_IN_1_fu_48_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_we0;
wire   [63:0] grp_output_collect_Pipeline_STREAM_IN_1_fu_48_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_d0;
wire    grp_output_collect_Pipeline_STREAM_IN_2_fu_58_ap_start;
wire    grp_output_collect_Pipeline_STREAM_IN_2_fu_58_ap_done;
wire    grp_output_collect_Pipeline_STREAM_IN_2_fu_58_ap_idle;
wire    grp_output_collect_Pipeline_STREAM_IN_2_fu_58_ap_ready;
wire    grp_output_collect_Pipeline_STREAM_IN_2_fu_58_Input_2_TREADY;
wire   [7:0] grp_output_collect_Pipeline_STREAM_IN_2_fu_58_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_address0;
wire    grp_output_collect_Pipeline_STREAM_IN_2_fu_58_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_ce0;
wire    grp_output_collect_Pipeline_STREAM_IN_2_fu_58_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_we0;
wire   [63:0] grp_output_collect_Pipeline_STREAM_IN_2_fu_58_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_d0;
wire   [7:0] grp_output_collect_Pipeline_STREAM_IN_2_fu_58_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_address0;
wire    grp_output_collect_Pipeline_STREAM_IN_2_fu_58_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_ce0;
wire    grp_output_collect_Pipeline_STREAM_IN_2_fu_58_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_we0;
wire   [63:0] grp_output_collect_Pipeline_STREAM_IN_2_fu_58_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_d0;
wire    grp_output_collect_Pipeline_STREAM_IN_3_fu_68_ap_start;
wire    grp_output_collect_Pipeline_STREAM_IN_3_fu_68_ap_done;
wire    grp_output_collect_Pipeline_STREAM_IN_3_fu_68_ap_idle;
wire    grp_output_collect_Pipeline_STREAM_IN_3_fu_68_ap_ready;
wire    grp_output_collect_Pipeline_STREAM_IN_3_fu_68_Input_3_TREADY;
wire   [7:0] grp_output_collect_Pipeline_STREAM_IN_3_fu_68_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_address0;
wire    grp_output_collect_Pipeline_STREAM_IN_3_fu_68_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_ce0;
wire    grp_output_collect_Pipeline_STREAM_IN_3_fu_68_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_we0;
wire   [63:0] grp_output_collect_Pipeline_STREAM_IN_3_fu_68_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_d0;
wire   [7:0] grp_output_collect_Pipeline_STREAM_IN_3_fu_68_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_address0;
wire    grp_output_collect_Pipeline_STREAM_IN_3_fu_68_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_ce0;
wire    grp_output_collect_Pipeline_STREAM_IN_3_fu_68_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_we0;
wire   [63:0] grp_output_collect_Pipeline_STREAM_IN_3_fu_68_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_d0;
wire    grp_output_collect_Pipeline_STREAM_IN_4_fu_78_ap_start;
wire    grp_output_collect_Pipeline_STREAM_IN_4_fu_78_ap_done;
wire    grp_output_collect_Pipeline_STREAM_IN_4_fu_78_ap_idle;
wire    grp_output_collect_Pipeline_STREAM_IN_4_fu_78_ap_ready;
wire    grp_output_collect_Pipeline_STREAM_IN_4_fu_78_Input_4_TREADY;
wire   [7:0] grp_output_collect_Pipeline_STREAM_IN_4_fu_78_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_address0;
wire    grp_output_collect_Pipeline_STREAM_IN_4_fu_78_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_ce0;
wire    grp_output_collect_Pipeline_STREAM_IN_4_fu_78_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_we0;
wire   [63:0] grp_output_collect_Pipeline_STREAM_IN_4_fu_78_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_d0;
wire   [7:0] grp_output_collect_Pipeline_STREAM_IN_4_fu_78_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_address0;
wire    grp_output_collect_Pipeline_STREAM_IN_4_fu_78_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_ce0;
wire    grp_output_collect_Pipeline_STREAM_IN_4_fu_78_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_we0;
wire   [63:0] grp_output_collect_Pipeline_STREAM_IN_4_fu_78_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_d0;
wire    grp_output_collect_Pipeline_STREAM_OUT_fu_88_ap_start;
wire    grp_output_collect_Pipeline_STREAM_OUT_fu_88_ap_done;
wire    grp_output_collect_Pipeline_STREAM_OUT_fu_88_ap_idle;
wire    grp_output_collect_Pipeline_STREAM_OUT_fu_88_ap_ready;
wire    grp_output_collect_Pipeline_STREAM_OUT_fu_88_Output_1_TREADY;
wire   [255:0] grp_output_collect_Pipeline_STREAM_OUT_fu_88_Output_1_TDATA;
wire    grp_output_collect_Pipeline_STREAM_OUT_fu_88_Output_1_TVALID;
wire   [7:0] grp_output_collect_Pipeline_STREAM_OUT_fu_88_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_address0;
wire    grp_output_collect_Pipeline_STREAM_OUT_fu_88_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_ce0;
wire   [7:0] grp_output_collect_Pipeline_STREAM_OUT_fu_88_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_address1;
wire    grp_output_collect_Pipeline_STREAM_OUT_fu_88_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_ce1;
wire   [7:0] grp_output_collect_Pipeline_STREAM_OUT_fu_88_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_address0;
wire    grp_output_collect_Pipeline_STREAM_OUT_fu_88_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_ce0;
wire   [7:0] grp_output_collect_Pipeline_STREAM_OUT_fu_88_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_address1;
wire    grp_output_collect_Pipeline_STREAM_OUT_fu_88_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_ce1;
reg    grp_output_collect_Pipeline_STREAM_IN_1_fu_48_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    grp_output_collect_Pipeline_STREAM_IN_2_fu_58_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg    grp_output_collect_Pipeline_STREAM_IN_3_fu_68_ap_start_reg;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
reg    grp_output_collect_Pipeline_STREAM_IN_4_fu_78_ap_start_reg;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
reg    grp_output_collect_Pipeline_STREAM_OUT_fu_88_ap_start_reg;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state16;
wire    regslice_both_Output_1_U_apdone_blk;
reg   [15:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
reg    ap_ST_fsm_state16_blk;
wire    regslice_both_Input_1_U_apdone_blk;
wire   [63:0] Input_1_TDATA_int_regslice;
wire    Input_1_TVALID_int_regslice;
reg    Input_1_TREADY_int_regslice;
wire    regslice_both_Input_1_U_ack_in;
wire    regslice_both_Input_2_U_apdone_blk;
wire   [63:0] Input_2_TDATA_int_regslice;
wire    Input_2_TVALID_int_regslice;
reg    Input_2_TREADY_int_regslice;
wire    regslice_both_Input_2_U_ack_in;
wire    regslice_both_Input_3_U_apdone_blk;
wire   [63:0] Input_3_TDATA_int_regslice;
wire    Input_3_TVALID_int_regslice;
reg    Input_3_TREADY_int_regslice;
wire    regslice_both_Input_3_U_ack_in;
wire    regslice_both_Input_4_U_apdone_blk;
wire   [63:0] Input_4_TDATA_int_regslice;
wire    Input_4_TVALID_int_regslice;
reg    Input_4_TREADY_int_regslice;
wire    regslice_both_Input_4_U_ack_in;
wire    Output_1_TREADY_int_regslice;
wire    regslice_both_Output_1_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 16'd1;
#0 grp_output_collect_Pipeline_STREAM_IN_1_fu_48_ap_start_reg = 1'b0;
#0 grp_output_collect_Pipeline_STREAM_IN_2_fu_58_ap_start_reg = 1'b0;
#0 grp_output_collect_Pipeline_STREAM_IN_3_fu_68_ap_start_reg = 1'b0;
#0 grp_output_collect_Pipeline_STREAM_IN_4_fu_78_ap_start_reg = 1'b0;
#0 grp_output_collect_Pipeline_STREAM_OUT_fu_88_ap_start_reg = 1'b0;
end

output_collect_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_RAM_AUTO_bkb #(
    .DataWidth( 64 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_address0),
    .ce0(output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_ce0),
    .we0(output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_we0),
    .d0(output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_d0),
    .q0(output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_q0),
    .address1(grp_output_collect_Pipeline_STREAM_OUT_fu_88_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_address1),
    .ce1(output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_ce1),
    .q1(output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_q1)
);

output_collect_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_RAM_AUTO_bkb #(
    .DataWidth( 64 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_address0),
    .ce0(output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_ce0),
    .we0(output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_we0),
    .d0(output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_d0),
    .q0(output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_q0),
    .address1(grp_output_collect_Pipeline_STREAM_OUT_fu_88_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_address1),
    .ce1(output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_ce1),
    .q1(output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_q1)
);

output_collect_output_collect_Pipeline_STREAM_IN_1 grp_output_collect_Pipeline_STREAM_IN_1_fu_48(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_output_collect_Pipeline_STREAM_IN_1_fu_48_ap_start),
    .ap_done(grp_output_collect_Pipeline_STREAM_IN_1_fu_48_ap_done),
    .ap_idle(grp_output_collect_Pipeline_STREAM_IN_1_fu_48_ap_idle),
    .ap_ready(grp_output_collect_Pipeline_STREAM_IN_1_fu_48_ap_ready),
    .Input_1_TVALID(Input_1_TVALID_int_regslice),
    .Input_1_TDATA(Input_1_TDATA_int_regslice),
    .Input_1_TREADY(grp_output_collect_Pipeline_STREAM_IN_1_fu_48_Input_1_TREADY),
    .output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_address0(grp_output_collect_Pipeline_STREAM_IN_1_fu_48_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_address0),
    .output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_ce0(grp_output_collect_Pipeline_STREAM_IN_1_fu_48_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_ce0),
    .output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_we0(grp_output_collect_Pipeline_STREAM_IN_1_fu_48_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_we0),
    .output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_d0(grp_output_collect_Pipeline_STREAM_IN_1_fu_48_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_d0),
    .output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_address0(grp_output_collect_Pipeline_STREAM_IN_1_fu_48_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_address0),
    .output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_ce0(grp_output_collect_Pipeline_STREAM_IN_1_fu_48_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_ce0),
    .output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_we0(grp_output_collect_Pipeline_STREAM_IN_1_fu_48_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_we0),
    .output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_d0(grp_output_collect_Pipeline_STREAM_IN_1_fu_48_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_d0)
);

output_collect_output_collect_Pipeline_STREAM_IN_2 grp_output_collect_Pipeline_STREAM_IN_2_fu_58(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_output_collect_Pipeline_STREAM_IN_2_fu_58_ap_start),
    .ap_done(grp_output_collect_Pipeline_STREAM_IN_2_fu_58_ap_done),
    .ap_idle(grp_output_collect_Pipeline_STREAM_IN_2_fu_58_ap_idle),
    .ap_ready(grp_output_collect_Pipeline_STREAM_IN_2_fu_58_ap_ready),
    .Input_2_TVALID(Input_2_TVALID_int_regslice),
    .Input_2_TDATA(Input_2_TDATA_int_regslice),
    .Input_2_TREADY(grp_output_collect_Pipeline_STREAM_IN_2_fu_58_Input_2_TREADY),
    .output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_address0(grp_output_collect_Pipeline_STREAM_IN_2_fu_58_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_address0),
    .output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_ce0(grp_output_collect_Pipeline_STREAM_IN_2_fu_58_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_ce0),
    .output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_we0(grp_output_collect_Pipeline_STREAM_IN_2_fu_58_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_we0),
    .output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_d0(grp_output_collect_Pipeline_STREAM_IN_2_fu_58_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_d0),
    .output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_address0(grp_output_collect_Pipeline_STREAM_IN_2_fu_58_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_address0),
    .output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_ce0(grp_output_collect_Pipeline_STREAM_IN_2_fu_58_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_ce0),
    .output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_we0(grp_output_collect_Pipeline_STREAM_IN_2_fu_58_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_we0),
    .output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_d0(grp_output_collect_Pipeline_STREAM_IN_2_fu_58_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_d0)
);

output_collect_output_collect_Pipeline_STREAM_IN_3 grp_output_collect_Pipeline_STREAM_IN_3_fu_68(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_output_collect_Pipeline_STREAM_IN_3_fu_68_ap_start),
    .ap_done(grp_output_collect_Pipeline_STREAM_IN_3_fu_68_ap_done),
    .ap_idle(grp_output_collect_Pipeline_STREAM_IN_3_fu_68_ap_idle),
    .ap_ready(grp_output_collect_Pipeline_STREAM_IN_3_fu_68_ap_ready),
    .Input_3_TVALID(Input_3_TVALID_int_regslice),
    .Input_3_TDATA(Input_3_TDATA_int_regslice),
    .Input_3_TREADY(grp_output_collect_Pipeline_STREAM_IN_3_fu_68_Input_3_TREADY),
    .output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_address0(grp_output_collect_Pipeline_STREAM_IN_3_fu_68_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_address0),
    .output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_ce0(grp_output_collect_Pipeline_STREAM_IN_3_fu_68_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_ce0),
    .output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_we0(grp_output_collect_Pipeline_STREAM_IN_3_fu_68_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_we0),
    .output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_d0(grp_output_collect_Pipeline_STREAM_IN_3_fu_68_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_d0),
    .output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_address0(grp_output_collect_Pipeline_STREAM_IN_3_fu_68_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_address0),
    .output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_ce0(grp_output_collect_Pipeline_STREAM_IN_3_fu_68_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_ce0),
    .output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_we0(grp_output_collect_Pipeline_STREAM_IN_3_fu_68_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_we0),
    .output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_d0(grp_output_collect_Pipeline_STREAM_IN_3_fu_68_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_d0)
);

output_collect_output_collect_Pipeline_STREAM_IN_4 grp_output_collect_Pipeline_STREAM_IN_4_fu_78(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_output_collect_Pipeline_STREAM_IN_4_fu_78_ap_start),
    .ap_done(grp_output_collect_Pipeline_STREAM_IN_4_fu_78_ap_done),
    .ap_idle(grp_output_collect_Pipeline_STREAM_IN_4_fu_78_ap_idle),
    .ap_ready(grp_output_collect_Pipeline_STREAM_IN_4_fu_78_ap_ready),
    .Input_4_TVALID(Input_4_TVALID_int_regslice),
    .Input_4_TDATA(Input_4_TDATA_int_regslice),
    .Input_4_TREADY(grp_output_collect_Pipeline_STREAM_IN_4_fu_78_Input_4_TREADY),
    .output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_address0(grp_output_collect_Pipeline_STREAM_IN_4_fu_78_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_address0),
    .output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_ce0(grp_output_collect_Pipeline_STREAM_IN_4_fu_78_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_ce0),
    .output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_we0(grp_output_collect_Pipeline_STREAM_IN_4_fu_78_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_we0),
    .output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_d0(grp_output_collect_Pipeline_STREAM_IN_4_fu_78_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_d0),
    .output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_address0(grp_output_collect_Pipeline_STREAM_IN_4_fu_78_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_address0),
    .output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_ce0(grp_output_collect_Pipeline_STREAM_IN_4_fu_78_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_ce0),
    .output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_we0(grp_output_collect_Pipeline_STREAM_IN_4_fu_78_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_we0),
    .output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_d0(grp_output_collect_Pipeline_STREAM_IN_4_fu_78_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_d0)
);

output_collect_output_collect_Pipeline_STREAM_OUT grp_output_collect_Pipeline_STREAM_OUT_fu_88(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_output_collect_Pipeline_STREAM_OUT_fu_88_ap_start),
    .ap_done(grp_output_collect_Pipeline_STREAM_OUT_fu_88_ap_done),
    .ap_idle(grp_output_collect_Pipeline_STREAM_OUT_fu_88_ap_idle),
    .ap_ready(grp_output_collect_Pipeline_STREAM_OUT_fu_88_ap_ready),
    .Output_1_TREADY(grp_output_collect_Pipeline_STREAM_OUT_fu_88_Output_1_TREADY),
    .Output_1_TDATA(grp_output_collect_Pipeline_STREAM_OUT_fu_88_Output_1_TDATA),
    .Output_1_TVALID(grp_output_collect_Pipeline_STREAM_OUT_fu_88_Output_1_TVALID),
    .output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_address0(grp_output_collect_Pipeline_STREAM_OUT_fu_88_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_address0),
    .output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_ce0(grp_output_collect_Pipeline_STREAM_OUT_fu_88_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_ce0),
    .output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_q0(output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_q0),
    .output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_address1(grp_output_collect_Pipeline_STREAM_OUT_fu_88_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_address1),
    .output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_ce1(grp_output_collect_Pipeline_STREAM_OUT_fu_88_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_ce1),
    .output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_q1(output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_q1),
    .output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_address0(grp_output_collect_Pipeline_STREAM_OUT_fu_88_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_address0),
    .output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_ce0(grp_output_collect_Pipeline_STREAM_OUT_fu_88_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_ce0),
    .output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_q0(output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_q0),
    .output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_address1(grp_output_collect_Pipeline_STREAM_OUT_fu_88_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_address1),
    .output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_ce1(grp_output_collect_Pipeline_STREAM_OUT_fu_88_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_ce1),
    .output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_q1(output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_q1)
);

output_collect_regslice_both #(
    .DataWidth( 64 ))
regslice_both_Input_1_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(Input_1_TDATA),
    .vld_in(Input_1_TVALID),
    .ack_in(regslice_both_Input_1_U_ack_in),
    .data_out(Input_1_TDATA_int_regslice),
    .vld_out(Input_1_TVALID_int_regslice),
    .ack_out(Input_1_TREADY_int_regslice),
    .apdone_blk(regslice_both_Input_1_U_apdone_blk)
);

output_collect_regslice_both #(
    .DataWidth( 64 ))
regslice_both_Input_2_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(Input_2_TDATA),
    .vld_in(Input_2_TVALID),
    .ack_in(regslice_both_Input_2_U_ack_in),
    .data_out(Input_2_TDATA_int_regslice),
    .vld_out(Input_2_TVALID_int_regslice),
    .ack_out(Input_2_TREADY_int_regslice),
    .apdone_blk(regslice_both_Input_2_U_apdone_blk)
);

output_collect_regslice_both #(
    .DataWidth( 64 ))
regslice_both_Input_3_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(Input_3_TDATA),
    .vld_in(Input_3_TVALID),
    .ack_in(regslice_both_Input_3_U_ack_in),
    .data_out(Input_3_TDATA_int_regslice),
    .vld_out(Input_3_TVALID_int_regslice),
    .ack_out(Input_3_TREADY_int_regslice),
    .apdone_blk(regslice_both_Input_3_U_apdone_blk)
);

output_collect_regslice_both #(
    .DataWidth( 64 ))
regslice_both_Input_4_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(Input_4_TDATA),
    .vld_in(Input_4_TVALID),
    .ack_in(regslice_both_Input_4_U_ack_in),
    .data_out(Input_4_TDATA_int_regslice),
    .vld_out(Input_4_TVALID_int_regslice),
    .ack_out(Input_4_TREADY_int_regslice),
    .apdone_blk(regslice_both_Input_4_U_apdone_blk)
);

output_collect_regslice_both #(
    .DataWidth( 256 ))
regslice_both_Output_1_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_output_collect_Pipeline_STREAM_OUT_fu_88_Output_1_TDATA),
    .vld_in(grp_output_collect_Pipeline_STREAM_OUT_fu_88_Output_1_TVALID),
    .ack_in(Output_1_TREADY_int_regslice),
    .data_out(Output_1_TDATA),
    .vld_out(regslice_both_Output_1_U_vld_out),
    .ack_out(Output_1_TREADY),
    .apdone_blk(regslice_both_Output_1_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_output_collect_Pipeline_STREAM_IN_1_fu_48_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_output_collect_Pipeline_STREAM_IN_1_fu_48_ap_start_reg <= 1'b1;
        end else if ((grp_output_collect_Pipeline_STREAM_IN_1_fu_48_ap_ready == 1'b1)) begin
            grp_output_collect_Pipeline_STREAM_IN_1_fu_48_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_output_collect_Pipeline_STREAM_IN_2_fu_58_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_output_collect_Pipeline_STREAM_IN_2_fu_58_ap_start_reg <= 1'b1;
        end else if ((grp_output_collect_Pipeline_STREAM_IN_2_fu_58_ap_ready == 1'b1)) begin
            grp_output_collect_Pipeline_STREAM_IN_2_fu_58_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_output_collect_Pipeline_STREAM_IN_3_fu_68_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state8)) begin
            grp_output_collect_Pipeline_STREAM_IN_3_fu_68_ap_start_reg <= 1'b1;
        end else if ((grp_output_collect_Pipeline_STREAM_IN_3_fu_68_ap_ready == 1'b1)) begin
            grp_output_collect_Pipeline_STREAM_IN_3_fu_68_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_output_collect_Pipeline_STREAM_IN_4_fu_78_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state11)) begin
            grp_output_collect_Pipeline_STREAM_IN_4_fu_78_ap_start_reg <= 1'b1;
        end else if ((grp_output_collect_Pipeline_STREAM_IN_4_fu_78_ap_ready == 1'b1)) begin
            grp_output_collect_Pipeline_STREAM_IN_4_fu_78_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_output_collect_Pipeline_STREAM_OUT_fu_88_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state14)) begin
            grp_output_collect_Pipeline_STREAM_OUT_fu_88_ap_start_reg <= 1'b1;
        end else if ((grp_output_collect_Pipeline_STREAM_OUT_fu_88_ap_ready == 1'b1)) begin
            grp_output_collect_Pipeline_STREAM_OUT_fu_88_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        Input_1_TREADY_int_regslice = grp_output_collect_Pipeline_STREAM_IN_1_fu_48_Input_1_TREADY;
    end else begin
        Input_1_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        Input_2_TREADY_int_regslice = grp_output_collect_Pipeline_STREAM_IN_2_fu_58_Input_2_TREADY;
    end else begin
        Input_2_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        Input_3_TREADY_int_regslice = grp_output_collect_Pipeline_STREAM_IN_3_fu_68_Input_3_TREADY;
    end else begin
        Input_3_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        Input_4_TREADY_int_regslice = grp_output_collect_Pipeline_STREAM_IN_4_fu_78_Input_4_TREADY;
    end else begin
        Input_4_TREADY_int_regslice = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((grp_output_collect_Pipeline_STREAM_IN_4_fu_78_ap_done == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

always @ (*) begin
    if ((grp_output_collect_Pipeline_STREAM_OUT_fu_88_ap_done == 1'b0)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_Output_1_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state16_blk = 1'b1;
    end else begin
        ap_ST_fsm_state16_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_output_collect_Pipeline_STREAM_IN_1_fu_48_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_output_collect_Pipeline_STREAM_IN_2_fu_58_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_output_collect_Pipeline_STREAM_IN_3_fu_68_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_Output_1_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state16))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_Output_1_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state16))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_address0 = grp_output_collect_Pipeline_STREAM_OUT_fu_88_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_address0 = grp_output_collect_Pipeline_STREAM_IN_4_fu_78_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_address0 = grp_output_collect_Pipeline_STREAM_IN_3_fu_68_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_address0 = grp_output_collect_Pipeline_STREAM_IN_2_fu_58_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_address0 = grp_output_collect_Pipeline_STREAM_IN_1_fu_48_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_address0;
    end else begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_ce0 = grp_output_collect_Pipeline_STREAM_OUT_fu_88_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_ce0 = grp_output_collect_Pipeline_STREAM_IN_4_fu_78_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_ce0 = grp_output_collect_Pipeline_STREAM_IN_3_fu_68_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_ce0 = grp_output_collect_Pipeline_STREAM_IN_2_fu_58_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_ce0 = grp_output_collect_Pipeline_STREAM_IN_1_fu_48_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_ce0;
    end else begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_ce1 = grp_output_collect_Pipeline_STREAM_OUT_fu_88_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_ce1;
    end else begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_d0 = grp_output_collect_Pipeline_STREAM_IN_4_fu_78_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_d0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_d0 = grp_output_collect_Pipeline_STREAM_IN_3_fu_68_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_d0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_d0 = grp_output_collect_Pipeline_STREAM_IN_2_fu_58_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_d0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_d0 = grp_output_collect_Pipeline_STREAM_IN_1_fu_48_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_d0;
    end else begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_we0 = grp_output_collect_Pipeline_STREAM_IN_4_fu_78_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_we0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_we0 = grp_output_collect_Pipeline_STREAM_IN_3_fu_68_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_we0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_we0 = grp_output_collect_Pipeline_STREAM_IN_2_fu_58_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_we0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_we0 = grp_output_collect_Pipeline_STREAM_IN_1_fu_48_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_we0;
    end else begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_address0 = grp_output_collect_Pipeline_STREAM_OUT_fu_88_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_address0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_address0 = grp_output_collect_Pipeline_STREAM_IN_4_fu_78_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_address0 = grp_output_collect_Pipeline_STREAM_IN_3_fu_68_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_address0 = grp_output_collect_Pipeline_STREAM_IN_2_fu_58_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_address0 = grp_output_collect_Pipeline_STREAM_IN_1_fu_48_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_address0;
    end else begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_ce0 = grp_output_collect_Pipeline_STREAM_OUT_fu_88_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_ce0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_ce0 = grp_output_collect_Pipeline_STREAM_IN_4_fu_78_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_ce0 = grp_output_collect_Pipeline_STREAM_IN_3_fu_68_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_ce0 = grp_output_collect_Pipeline_STREAM_IN_2_fu_58_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_ce0 = grp_output_collect_Pipeline_STREAM_IN_1_fu_48_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_ce0;
    end else begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_ce1 = grp_output_collect_Pipeline_STREAM_OUT_fu_88_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_ce1;
    end else begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_d0 = grp_output_collect_Pipeline_STREAM_IN_4_fu_78_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_d0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_d0 = grp_output_collect_Pipeline_STREAM_IN_3_fu_68_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_d0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_d0 = grp_output_collect_Pipeline_STREAM_IN_2_fu_58_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_d0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_d0 = grp_output_collect_Pipeline_STREAM_IN_1_fu_48_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_d0;
    end else begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_we0 = grp_output_collect_Pipeline_STREAM_IN_4_fu_78_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_we0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_we0 = grp_output_collect_Pipeline_STREAM_IN_3_fu_68_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_we0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_we0 = grp_output_collect_Pipeline_STREAM_IN_2_fu_58_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_we0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_we0 = grp_output_collect_Pipeline_STREAM_IN_1_fu_48_output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_we0;
    end else begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_output_collect_Pipeline_STREAM_IN_1_fu_48_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_output_collect_Pipeline_STREAM_IN_2_fu_58_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & (grp_output_collect_Pipeline_STREAM_IN_3_fu_68_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((1'b1 == ap_CS_fsm_state12) & (grp_output_collect_Pipeline_STREAM_IN_4_fu_78_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((1'b1 == ap_CS_fsm_state15) & (grp_output_collect_Pipeline_STREAM_OUT_fu_88_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            if (((regslice_both_Output_1_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Input_1_TREADY = regslice_both_Input_1_U_ack_in;

assign Input_2_TREADY = regslice_both_Input_2_U_ack_in;

assign Input_3_TREADY = regslice_both_Input_3_U_ack_in;

assign Input_4_TREADY = regslice_both_Input_4_U_ack_in;

assign Output_1_TVALID = regslice_both_Output_1_U_vld_out;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_output_collect_Pipeline_STREAM_IN_1_fu_48_ap_start = grp_output_collect_Pipeline_STREAM_IN_1_fu_48_ap_start_reg;

assign grp_output_collect_Pipeline_STREAM_IN_2_fu_58_ap_start = grp_output_collect_Pipeline_STREAM_IN_2_fu_58_ap_start_reg;

assign grp_output_collect_Pipeline_STREAM_IN_3_fu_68_ap_start = grp_output_collect_Pipeline_STREAM_IN_3_fu_68_ap_start_reg;

assign grp_output_collect_Pipeline_STREAM_IN_4_fu_78_ap_start = grp_output_collect_Pipeline_STREAM_IN_4_fu_78_ap_start_reg;

assign grp_output_collect_Pipeline_STREAM_OUT_fu_88_Output_1_TREADY = (ap_CS_fsm_state15 & Output_1_TREADY_int_regslice);

assign grp_output_collect_Pipeline_STREAM_OUT_fu_88_ap_start = grp_output_collect_Pipeline_STREAM_OUT_fu_88_ap_start_reg;

endmodule //output_collect
