// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module output_collect_output_collect_Pipeline_STREAM_IN_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        Input_1_TVALID,
        Input_1_TDATA,
        Input_1_TREADY,
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_address0,
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_ce0,
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_we0,
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_d0,
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_address0,
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_ce0,
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_we0,
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_d0
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   Input_1_TVALID;
input  [63:0] Input_1_TDATA;
output   Input_1_TREADY;
output  [7:0] output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_address0;
output   output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_ce0;
output   output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_we0;
output  [63:0] output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_d0;
output  [7:0] output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_address0;
output   output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_ce0;
output   output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_we0;
output  [63:0] output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_d0;

reg ap_idle;
reg Input_1_TREADY;
reg output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_ce0;
reg output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_we0;
reg output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_ce0;
reg output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln21_fu_90_p2;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    Input_1_TDATA_blk_n;
wire   [63:0] zext_ln23_fu_112_p1;
reg   [7:0] i_fu_44;
wire   [7:0] add_ln21_fu_96_p2;
wire    ap_loop_init;
reg   [7:0] ap_sig_allocacmp_i_3;
wire   [0:0] trunc_ln23_fu_118_p1;
wire   [5:0] lshr_ln_fu_102_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
reg    ap_condition_122;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

output_collect_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_start_int == 1'b0) | ((1'b0 == Input_1_TVALID) & (icmp_ln21_fu_90_p2 == 1'd0))) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_122)) begin
        if ((icmp_ln21_fu_90_p2 == 1'd0)) begin
            i_fu_44 <= add_ln21_fu_96_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_44 <= 8'd0;
        end
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_90_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        Input_1_TDATA_blk_n = Input_1_TVALID;
    end else begin
        Input_1_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == Input_1_TVALID) & (icmp_ln21_fu_90_p2 == 1'd0))) & (icmp_ln21_fu_90_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        Input_1_TREADY = 1'b1;
    end else begin
        Input_1_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) | ((1'b0 == Input_1_TVALID) & (icmp_ln21_fu_90_p2 == 1'd0)))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == Input_1_TVALID) & (icmp_ln21_fu_90_p2 == 1'd0))) & (icmp_ln21_fu_90_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == Input_1_TVALID) & (icmp_ln21_fu_90_p2 == 1'd0))) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == Input_1_TVALID) & (icmp_ln21_fu_90_p2 == 1'd0))) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_i_3 = 8'd0;
    end else begin
        ap_sig_allocacmp_i_3 = i_fu_44;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == Input_1_TVALID) & (icmp_ln21_fu_90_p2 == 1'd0))) & (1'b1 == ap_CS_fsm_state1))) begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_ce0 = 1'b1;
    end else begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == Input_1_TVALID) & (icmp_ln21_fu_90_p2 == 1'd0))) & (trunc_ln23_fu_118_p1 == 1'd0) & (icmp_ln21_fu_90_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_we0 = 1'b1;
    end else begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == Input_1_TVALID) & (icmp_ln21_fu_90_p2 == 1'd0))) & (1'b1 == ap_CS_fsm_state1))) begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_ce0 = 1'b1;
    end else begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == Input_1_TVALID) & (icmp_ln21_fu_90_p2 == 1'd0))) & (trunc_ln23_fu_118_p1 == 1'd1) & (icmp_ln21_fu_90_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_we0 = 1'b1;
    end else begin
        output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln21_fu_96_p2 = (ap_sig_allocacmp_i_3 + 8'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((1'b0 == Input_1_TVALID) & (icmp_ln21_fu_90_p2 == 1'd0)));
end

always @ (*) begin
    ap_condition_122 = (~((ap_start_int == 1'b0) | ((1'b0 == Input_1_TVALID) & (icmp_ln21_fu_90_p2 == 1'd0))) & (1'b1 == ap_CS_fsm_state1));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln21_fu_90_p2 = ((ap_sig_allocacmp_i_3 == 8'd128) ? 1'b1 : 1'b0);

assign lshr_ln_fu_102_p4 = {{ap_sig_allocacmp_i_3[6:1]}};

assign output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_address0 = zext_ln23_fu_112_p1;

assign output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_1_d0 = Input_1_TDATA;

assign output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_address0 = zext_ln23_fu_112_p1;

assign output_collect_stream_stream_stream_stream_stream_ap_uint_0_theta_d0 = Input_1_TDATA;

assign trunc_ln23_fu_118_p1 = ap_sig_allocacmp_i_3[0:0];

assign zext_ln23_fu_112_p1 = lshr_ln_fu_102_p4;

endmodule //output_collect_output_collect_Pipeline_STREAM_IN_1
