// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 


module dut #(
    parameter OUTPUT_SIZE = 64
  ) (
  input [63:0] Loop_VITIS_LOOP_39_1_proc1_U0_v1_buffer_V_din,
  input Loop_VITIS_LOOP_39_1_proc1_U0_v1_buffer_V_write,
  output v1_buffer_V_full_n,

  input [511:0] Loop_VITIS_LOOP_43_3_proc3_U0_v2_buffer_V_din ,
  input Loop_VITIS_LOOP_43_3_proc3_U0_v2_buffer_V_write,
  output v2_buffer_V_full_n,

  output [63:0] v1_buffer_V_dout,
  output v1_buffer_V_empty_n,
  input Loop_VITIS_LOOP_40_2_proc2_U0_v1_buffer_V_read,

  output [511:0] v2_buffer_V_dout, // data out
  output v2_buffer_V_empty_n,
  input Loop_VITIS_LOOP_44_4_proc4_U0_v2_buffer_V_read,
  

  input clk_200,
  input clk_250,
  input clk_300,
  input clk_350,
  input clk_400,

  input rst_n_300,
  input ap_start
);

  mono #(.OUTPUT_SIZE(OUTPUT_SIZE))mono_inst(
    .clk_200(clk_200),
    .clk_250(clk_250),
    .clk_300(clk_300),
    .clk_350(clk_350),
    .clk_400(clk_400),

    .Input_1_TDATA(Loop_VITIS_LOOP_39_1_proc1_U0_v1_buffer_V_din),
    .Input_1_TVALID(Loop_VITIS_LOOP_39_1_proc1_U0_v1_buffer_V_write),
    .Input_1_TREADY(v1_buffer_V_full_n),
    .Output_1_TDATA(v1_buffer_V_dout),
    .Output_1_TVALID(v1_buffer_V_empty_n),
    .Output_1_TREADY(Loop_VITIS_LOOP_40_2_proc2_U0_v1_buffer_V_read),

    .ap_rst_n(rst_n_300),
    .Input_2_TDATA(Loop_VITIS_LOOP_43_3_proc3_U0_v2_buffer_V_din),
    .Input_2_TVALID(Loop_VITIS_LOOP_43_3_proc3_U0_v2_buffer_V_write),
    .Input_2_TREADY(v2_buffer_V_full_n),
    .Output_2_TDATA(v2_buffer_V_dout),
    .Output_2_TVALID(v2_buffer_V_empty_n),
    .Output_2_TREADY(Loop_VITIS_LOOP_44_4_proc4_U0_v2_buffer_V_read),
    .ap_start(ap_start)

    );


endmodule


