// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module zculling_i1_zculling_i1_Pipeline_ZCULLING (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        Input_1_TVALID,
        tmp_V_cast,
        Input_1_TDATA,
        Input_1_TREADY,
        pixels_x_V_address0,
        pixels_x_V_ce0,
        pixels_x_V_we0,
        pixels_x_V_d0,
        pixels_y_V_address0,
        pixels_y_V_ce0,
        pixels_y_V_we0,
        pixels_y_V_d0,
        pixels_color_V_address0,
        pixels_color_V_ce0,
        pixels_color_V_we0,
        pixels_color_V_d0,
        pixel_cntr_V_out,
        pixel_cntr_V_out_ap_vld,
        z_buffer_V_address0,
        z_buffer_V_ce0,
        z_buffer_V_we0,
        z_buffer_V_d0,
        z_buffer_V_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   Input_1_TVALID;
input  [15:0] tmp_V_cast;
input  [31:0] Input_1_TDATA;
output   Input_1_TREADY;
output  [8:0] pixels_x_V_address0;
output   pixels_x_V_ce0;
output   pixels_x_V_we0;
output  [7:0] pixels_x_V_d0;
output  [8:0] pixels_y_V_address0;
output   pixels_y_V_ce0;
output   pixels_y_V_we0;
output  [7:0] pixels_y_V_d0;
output  [8:0] pixels_color_V_address0;
output   pixels_color_V_ce0;
output   pixels_color_V_we0;
output  [7:0] pixels_color_V_d0;
output  [15:0] pixel_cntr_V_out;
output   pixel_cntr_V_out_ap_vld;
output  [15:0] z_buffer_V_address0;
output   z_buffer_V_ce0;
output   z_buffer_V_we0;
output  [7:0] z_buffer_V_d0;
input  [7:0] z_buffer_V_q0;

reg ap_idle;
reg Input_1_TREADY;
reg pixels_x_V_ce0;
reg pixels_x_V_we0;
reg pixels_y_V_ce0;
reg pixels_y_V_we0;
reg pixels_color_V_ce0;
reg pixels_color_V_we0;
reg pixel_cntr_V_out_ap_vld;
reg[15:0] z_buffer_V_address0;
reg z_buffer_V_ce0;
reg z_buffer_V_we0;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln42_fu_152_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage1;
reg   [0:0] icmp_ln42_reg_257;
reg    ap_block_state2_pp0_stage1_iter0;
reg    ap_block_pp0_stage1_subdone;
reg    Input_1_TDATA_blk_n;
wire    ap_block_pp0_stage1;
wire    ap_block_pp0_stage0_11001;
wire   [7:0] fragment_x_V_fu_169_p1;
reg   [7:0] fragment_x_V_reg_261;
reg    ap_block_pp0_stage1_11001;
reg   [7:0] fragment_y_V_reg_266;
reg   [7:0] fragment_z_V_reg_271;
reg   [7:0] fragment_color_V_reg_277;
reg   [15:0] z_buffer_V_addr_1_reg_282;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [63:0] zext_ln1073_fu_207_p1;
wire   [63:0] zext_ln587_fu_220_p1;
wire    ap_block_pp0_stage0;
wire   [0:0] icmp_ln1073_fu_212_p2;
reg   [15:0] n_V_fu_60;
wire   [15:0] n_V_2_fu_158_p2;
wire    ap_loop_init;
reg   [15:0] ap_sig_allocacmp_n_V_1;
reg   [15:0] pixel_cntr_V_fu_64;
wire   [15:0] pixel_cntr_V_1_fu_227_p2;
wire    ap_block_pp0_stage0_01001;
wire   [15:0] trunc_ln1073_fu_203_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_1to1;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

zculling_i1_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln42_fu_152_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            n_V_fu_60 <= n_V_2_fu_158_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            n_V_fu_60 <= 16'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            pixel_cntr_V_fu_64 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln1073_fu_212_p2 == 1'd1))) begin
            pixel_cntr_V_fu_64 <= pixel_cntr_V_1_fu_227_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln42_reg_257 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        fragment_color_V_reg_277 <= {{Input_1_TDATA[31:24]}};
        fragment_x_V_reg_261 <= fragment_x_V_fu_169_p1;
        fragment_y_V_reg_266 <= {{Input_1_TDATA[15:8]}};
        fragment_z_V_reg_271 <= {{Input_1_TDATA[23:16]}};
        z_buffer_V_addr_1_reg_282 <= zext_ln1073_fu_207_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln42_reg_257 <= icmp_ln42_fu_152_p2;
    end
end

always @ (*) begin
    if (((icmp_ln42_reg_257 == 1'd0) & (1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        Input_1_TDATA_blk_n = Input_1_TVALID;
    end else begin
        Input_1_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln42_reg_257 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        Input_1_TREADY = 1'b1;
    end else begin
        Input_1_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln42_fu_152_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_n_V_1 = 16'd0;
    end else begin
        ap_sig_allocacmp_n_V_1 = n_V_fu_60;
    end
end

always @ (*) begin
    if (((icmp_ln42_fu_152_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pixel_cntr_V_out_ap_vld = 1'b1;
    end else begin
        pixel_cntr_V_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pixels_color_V_ce0 = 1'b1;
    end else begin
        pixels_color_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1073_fu_212_p2 == 1'd1))) begin
        pixels_color_V_we0 = 1'b1;
    end else begin
        pixels_color_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pixels_x_V_ce0 = 1'b1;
    end else begin
        pixels_x_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1073_fu_212_p2 == 1'd1))) begin
        pixels_x_V_we0 = 1'b1;
    end else begin
        pixels_x_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pixels_y_V_ce0 = 1'b1;
    end else begin
        pixels_y_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1073_fu_212_p2 == 1'd1))) begin
        pixels_y_V_we0 = 1'b1;
    end else begin
        pixels_y_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        z_buffer_V_address0 = z_buffer_V_addr_1_reg_282;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        z_buffer_V_address0 = zext_ln1073_fu_207_p1;
    end else begin
        z_buffer_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        z_buffer_V_ce0 = 1'b1;
    end else begin
        z_buffer_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1073_fu_212_p2 == 1'd1))) begin
        z_buffer_V_we0 = 1'b1;
    end else begin
        z_buffer_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001 = ((icmp_ln42_reg_257 == 1'd0) & (1'b0 == Input_1_TVALID) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((icmp_ln42_reg_257 == 1'd0) & (1'b0 == Input_1_TVALID) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0 = ((icmp_ln42_reg_257 == 1'd0) & (1'b0 == Input_1_TVALID));
end

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign fragment_x_V_fu_169_p1 = Input_1_TDATA[7:0];

assign icmp_ln1073_fu_212_p2 = ((z_buffer_V_q0 > fragment_z_V_reg_271) ? 1'b1 : 1'b0);

assign icmp_ln42_fu_152_p2 = ((ap_sig_allocacmp_n_V_1 == tmp_V_cast) ? 1'b1 : 1'b0);

assign n_V_2_fu_158_p2 = (ap_sig_allocacmp_n_V_1 + 16'd1);

assign pixel_cntr_V_1_fu_227_p2 = (pixel_cntr_V_fu_64 + 16'd1);

assign pixel_cntr_V_out = pixel_cntr_V_fu_64;

assign pixels_color_V_address0 = zext_ln587_fu_220_p1;

assign pixels_color_V_d0 = fragment_color_V_reg_277;

assign pixels_x_V_address0 = zext_ln587_fu_220_p1;

assign pixels_x_V_d0 = fragment_x_V_reg_261;

assign pixels_y_V_address0 = zext_ln587_fu_220_p1;

assign pixels_y_V_d0 = fragment_y_V_reg_266;

assign trunc_ln1073_fu_203_p1 = Input_1_TDATA[15:0];

assign z_buffer_V_d0 = fragment_z_V_reg_271;

assign zext_ln1073_fu_207_p1 = trunc_ln1073_fu_203_p1;

assign zext_ln587_fu_220_p1 = pixel_cntr_V_fu_64;

endmodule //zculling_i1_zculling_i1_Pipeline_ZCULLING
